baseURL = "https://hirethesepeople.com/"
languageCode = "en-us"
title = "Hire These People"
theme = "ananke"
publishDir = "docs"

[taxonomies]
  category = "companies"
  tag = "roles"

pygmentsUseClasses = true # enable theme-defined highlight style

[author]
name = "Hiring Manager"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 200
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  github = "https://github.com/erikng/hirethesepeople"

# Menu links along the sidebar navigation.
[[menu.main]]
name = "Employees"
identifier = "employees"
url = "/employees/"
weight = 1

[[menu.main]]
identifier = "companies"
name = "Companies"
url = "/companies/"
weight = 2

[[menu.main]]
identifier = "roles"
name = "Roles"
url = "/roles/"
weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true
